kind = "web"
previewPath = "/"
title = "Boioot"
version = "1.0.0"
id = "default-boioot-frontend"

[[services]]
localPort = 3000
name = "Boioot Frontend"
paths = ["/"]

[services.development]
run = "until curl -sf http://localhost:3000 > /dev/null 2>&1; do sleep 1; done && sleep infinity"
