# fly.toml — backend-bold-snowflake-8206
# See https://fly.io/docs/reference/configuration/

app            = 'backend-bold-snowflake-8206'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port        = 8080
  force_https          = false
  min_machines_running = 1
  auto_stop_machines   = false
  auto_start_machines  = true

  [[http_service.checks]]
    grace_period = "10s"
    interval     = "30s"
    method       = "GET"
    path         = "/health"
    timeout      = "5s"

[[vm]]
  memory    = '1gb'
  cpu_kind  = 'shared'
  cpus      = 1
  memory_mb = 1024
