// <auto-generated />
using Boioot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Boioot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BoiootDbContext))]
    [Migration("20260505100000_ExpandAgencyProfile")]
    partial class ExpandAgencyProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal — runtime only needs Up()/Down() for migration execution.
            // AgencyProfiles table is managed via EnsureTableAsync raw SQL in controllers
            // and via this migration's Up() method.
        }
    }
}
