// <auto-generated />
using System;
using Boioot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boioot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BoiootDbContext))]
    [Migration("20260415120000_AddUserImages")]
    partial class AddUserImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal — runtime only needs Up()/Down() for migration execution.
            // Full model snapshot is maintained by EnsureCreated() path (PostgreSQL fresh DB).
        }
    }
}
