// <auto-generated />
using System;
using Boioot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boioot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BoiootDbContext))]
    [Migration("20260323121520_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Boioot.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("CreatedByUserId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid?>("PlanId");

                    b.Property<Guid?>("PrimaryAdminUserId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AccountType");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlanId");

                    b.HasIndex("PrimaryAdminUserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.AccountUser", b =>
                {
                    b.Property<Guid>("AccountId");

                    b.Property<Guid>("UserId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsPrimary");

                    b.Property<DateTime>("JoinedAt");

                    b.Property<string>("OrganizationUserRole")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountUsers");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bio")
                        .HasMaxLength(1000);

                    b.Property<Guid?>("BrokerId");

                    b.Property<Guid?>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("SortOrder");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("BlogCategories");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<string>("CoverImageAlt");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("CreatedByUserId");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsFeatured");

                    b.Property<string>("OgDescription");

                    b.Property<string>("OgTitle");

                    b.Property<DateTime?>("PublishedAt");

                    b.Property<Guid?>("PublishedByUserId");

                    b.Property<int?>("ReadTimeMinutes");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(1000);

                    b.Property<string>("SeoDescriptionMode")
                        .IsRequired();

                    b.Property<string>("SeoMode")
                        .IsRequired();

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(500);

                    b.Property<string>("SeoTitleMode")
                        .IsRequired();

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("SlugMode")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid?>("UpdatedByUserId");

                    b.Property<int>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BlogPostCategory", b =>
                {
                    b.Property<Guid>("BlogPostId");

                    b.Property<Guid>("BlogCategoryId");

                    b.HasKey("BlogPostId", "BlogCategoryId");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("BlogPostCategories");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BlogSeoSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DefaultBlogListSeoDescription")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("DefaultBlogListSeoTitle")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("DefaultOgDescriptionTemplate")
                        .IsRequired();

                    b.Property<string>("DefaultOgTitleTemplate")
                        .IsRequired();

                    b.Property<string>("DefaultPostSeoDescriptionTemplate")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("DefaultPostSeoTitleTemplate")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("BlogSeoSettings", (string)null);
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BuyerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("IsPublished");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("PropertyType")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BuyerRequests");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BuyerRequestComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BuyerRequestId");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BuyerRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("BuyerRequestComments");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(300);

                    b.Property<string>("City")
                        .HasMaxLength(100);

                    b.Property<string>("CompanyType")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Email")
                        .HasMaxLength(200);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsProfileComplete");

                    b.Property<bool>("IsVerified");

                    b.Property<double?>("Latitude");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500);

                    b.Property<double?>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(150);

                    b.Property<string>("Phone")
                        .HasMaxLength(30);

                    b.Property<string>("Province");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("LastMessageAt");

                    b.Property<Guid?>("ProjectId");

                    b.Property<Guid?>("PropertyId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("User1Id");

                    b.Property<Guid>("User2Id");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("PropertyId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.FeatureDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("FeatureGroup")
                        .HasMaxLength(100);

                    b.Property<string>("Icon");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("FeatureGroup");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureDefinitions");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdminNote");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4);

                    b.Property<DateTime?>("ApprovedAt");

                    b.Property<Guid?>("ApprovedBy");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired();

                    b.Property<DateTime?>("ExpiresAt");

                    b.Property<string>("ExternalRef");

                    b.Property<Guid>("PlanPricingId");

                    b.Property<string>("ProviderName")
                        .IsRequired();

                    b.Property<DateTime?>("RejectedAt");

                    b.Property<Guid?>("RejectedBy");

                    b.Property<int>("Status");

                    b.Property<string>("StripeSessionUrl");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PlanPricingId");

                    b.HasIndex("UserId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.LimitDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppliesToScope")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Unit")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasDefaultValue("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToScope");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("LimitDefinitions");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.LocationCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasDefaultValue("");

                    b.Property<string>("Province")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasDefaultValue("");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("LocationCities");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.LocationNeighborhood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasDefaultValue("");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("LocationNeighborhoods");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AttachmentData");

                    b.Property<string>("AttachmentName");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<Guid>("ConversationId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsRead");

                    b.Property<Guid>("SenderId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsRead");

                    b.Property<string>("RelatedEntityId");

                    b.Property<string>("RelatedEntityType");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.OwnershipTypeConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Label")
                        .IsRequired();

                    b.Property<int>("Order");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("OwnershipTypeConfigs");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PaymentProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("ImageUrl")
                        .IsRequired();

                    b.Property<Guid>("InvoiceId");

                    b.Property<string>("Notes");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("PaymentProofs");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgentLimit");

                    b.Property<bool>("AllowAddOns");

                    b.Property<bool>("AllowDowngrade");

                    b.Property<bool>("AllowUpgrade");

                    b.Property<bool>("AnalyticsAccess")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("ApplicableAccountType")
                        .HasMaxLength(50);

                    b.Property<bool>("AutoDowngradeOnExpiry");

                    b.Property<bool>("AvailableForSelfSignup");

                    b.Property<string>("BadgeText");

                    b.Property<decimal>("BasePriceMonthly")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PriceMonthly");

                    b.Property<decimal>("BasePriceYearly")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PriceYearly");

                    b.Property<string>("BillingMode")
                        .IsRequired();

                    b.Property<string>("Code")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<int>("DisplayOrder");

                    b.Property<int>("FeaturedSlots");

                    b.Property<string>("Features")
                        .HasMaxLength(2000);

                    b.Property<bool>("HasTrial");

                    b.Property<int>("ImageLimitPerListing")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(5);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDefaultForNewUsers");

                    b.Property<bool>("IsPublic");

                    b.Property<bool>("IsRecommended");

                    b.Property<int>("ListingLimit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PlanCategory");

                    b.Property<string>("PlanColor");

                    b.Property<int>("ProjectLimit");

                    b.Property<int>("Rank");

                    b.Property<bool>("RequiresAdminApproval");

                    b.Property<bool>("RequiresPaymentForTrial");

                    b.Property<int>("TrialDays");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<bool>("VideoAllowed")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ApplicableAccountType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("Code IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("FeatureDefinitionId");

                    b.Property<bool>("IsEnabled");

                    b.Property<Guid>("SubscriptionPlanId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("FeatureDefinitionId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("SubscriptionPlanId", "FeatureDefinitionId")
                        .IsUnique();

                    b.ToTable("PlanFeatures");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PlanLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("LimitDefinitionId");

                    b.Property<Guid>("SubscriptionPlanId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("LimitDefinitionId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("SubscriptionPlanId", "LimitDefinitionId")
                        .IsUnique();

                    b.ToTable("PlanLimits");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PlanPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BillingCycle")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CurrencyCode")
                        .IsRequired();

                    b.Property<string>("ExternalPriceId");

                    b.Property<string>("ExternalProvider");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsPublic");

                    b.Property<Guid>("PlanId");

                    b.Property<decimal>("PriceAmount")
                        .HasPrecision(18, 4);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanPricings");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(300);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeliveryDate");

                    b.Property<string>("Description")
                        .HasMaxLength(3000);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<double?>("Latitude");

                    b.Property<double?>("Longitude");

                    b.Property<string>("Province");

                    b.Property<decimal?>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Status");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.ProjectImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("IsPrimary");

                    b.Property<int>("Order");

                    b.Property<Guid>("ProjectId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectImages");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AccountId");

                    b.Property<string>("Address")
                        .HasMaxLength(300);

                    b.Property<Guid?>("AgentId");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Bathrooms");

                    b.Property<int?>("Bedrooms");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("CommissionType");

                    b.Property<decimal?>("CommissionValue")
                        .HasPrecision(18, 4);

                    b.Property<Guid>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("CreatedByCompanyId");

                    b.Property<string>("CreatedByRole")
                        .IsRequired();

                    b.Property<string>("CreatedByUserId")
                        .IsRequired();

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasDefaultValue("SYP");

                    b.Property<string>("Description")
                        .HasMaxLength(3000);

                    b.Property<string>("Features");

                    b.Property<string>("Floor");

                    b.Property<int?>("HallsCount");

                    b.Property<bool>("HasCommission");

                    b.Property<int?>("InstallmentsCount");

                    b.Property<bool>("IsDeleted");

                    b.Property<double?>("Latitude");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<double?>("Longitude");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(150);

                    b.Property<string>("OwnerId");

                    b.Property<string>("OwnershipType");

                    b.Property<string>("PaymentType")
                        .IsRequired();

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PropertyAge");

                    b.Property<string>("Province");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("VideoUrl");

                    b.Property<int>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AgentId");

                    b.HasIndex("City");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PropertyAmenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("GroupAr")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Order");

                    b.ToTable("PropertyAmenities");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PropertyAmenitySelection", b =>
                {
                    b.Property<Guid>("PropertyId");

                    b.Property<Guid>("AmenityId");

                    b.HasKey("PropertyId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyAmenitySelections");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("IsPrimary");

                    b.Property<int>("Order");

                    b.Property<Guid>("PropertyId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PropertyListingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("PropertyListingTypes");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PropertyTypeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Icon")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<string>("Label")
                        .IsRequired();

                    b.Property<int>("Order");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PropertyTypeConfigs");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.RbacPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Boioot.Domain.Entities.RbacRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Boioot.Domain.Entities.RbacRolePermission", b =>
                {
                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("PermissionId");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Boioot.Domain.Entities.RbacUserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .HasMaxLength(200);

                    b.Property<string>("Message")
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid?>("ProjectId");

                    b.Property<Guid?>("PropertyId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Rating");

                    b.Property<Guid>("ReviewerId");

                    b.Property<Guid>("TargetId");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "\"Rating\" >= 1 AND \"Rating\" <= 5");
                        });
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<bool>("AutoRenew");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("PaymentRef")
                        .HasMaxLength(200);

                    b.Property<Guid>("PlanId");

                    b.Property<Guid?>("PricingId");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("EndDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("PlanId");

                    b.HasIndex("Status");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.SubscriptionPaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<DateTime?>("ActivatedAt");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4);

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(1000);

                    b.Property<string>("ExternalPaymentReference")
                        .HasMaxLength(500);

                    b.Property<string>("PaymentFlowType")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ReceiptFileName")
                        .HasMaxLength(300);

                    b.Property<string>("ReceiptImageUrl")
                        .HasMaxLength(2000);

                    b.Property<Guid>("RequestedPlanId");

                    b.Property<Guid?>("RequestedPricingId");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("ReviewedAt");

                    b.Property<Guid?>("ReviewedByUserId");

                    b.Property<Guid?>("SalesRepresentativeId");

                    b.Property<string>("SalesRepresentativeName")
                        .HasMaxLength(200);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PaymentFlowType");

                    b.HasIndex("PaymentMethod");

                    b.HasIndex("RequestedPlanId");

                    b.HasIndex("Status");

                    b.ToTable("SubscriptionPaymentRequests");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Phone")
                        .HasMaxLength(30);

                    b.Property<string>("ProfileImageUrl");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("TrialListingsUsed");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Account", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.Plan", "Plan")
                        .WithMany("Accounts")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Boioot.Domain.Entities.User", "PrimaryAdminUser")
                        .WithMany()
                        .HasForeignKey("PrimaryAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Plan");

                    b.Navigation("PrimaryAdminUser");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.AccountUser", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Account", "Account")
                        .WithMany("AccountUsers")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.User", "User")
                        .WithMany("AccountUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Agent", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Company", "Company")
                        .WithMany("Agents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Boioot.Domain.Entities.User", "User")
                        .WithOne("Agent")
                        .HasForeignKey("Boioot.Domain.Entities.Agent", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BlogPost", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.User", "PublishedBy")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Boioot.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("PublishedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BlogPostCategory", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.BlogCategory", "BlogCategory")
                        .WithMany("BlogPostCategories")
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.BlogPost", "BlogPost")
                        .WithMany("BlogPostCategories")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogCategory");

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BuyerRequest", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BuyerRequestComment", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.BuyerRequest", "BuyerRequest")
                        .WithMany()
                        .HasForeignKey("BuyerRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Boioot.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Boioot.Domain.Entities.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Property");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.PlanPricing", "PlanPricing")
                        .WithMany()
                        .HasForeignKey("PlanPricingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPricing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Message", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PaymentProof", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Invoice", "Invoice")
                        .WithOne("PaymentProof")
                        .HasForeignKey("Boioot.Domain.Entities.PaymentProof", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PlanFeature", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.FeatureDefinition", "FeatureDefinition")
                        .WithMany()
                        .HasForeignKey("FeatureDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureDefinition");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PlanLimit", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.LimitDefinition", "LimitDefinition")
                        .WithMany()
                        .HasForeignKey("LimitDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanLimits")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LimitDefinition");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PlanPricing", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanPricings")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Project", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.ProjectImage", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Property", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Agent", "Agent")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Boioot.Domain.Entities.Company", "Company")
                        .WithMany("Properties")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PropertyAmenitySelection", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.PropertyAmenity", "Amenity")
                        .WithMany("Selections")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.Property", "Property")
                        .WithMany("AmenitySelections")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PropertyImage", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.RbacRolePermission", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.RbacPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.RbacRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.RbacUserRole", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.RbacRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Request", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Project", "Project")
                        .WithMany("Requests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Boioot.Domain.Entities.Property", "Property")
                        .WithMany("Requests")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Boioot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Review", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Account", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.SubscriptionPaymentRequest", b =>
                {
                    b.HasOne("Boioot.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boioot.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("RequestedPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Account", b =>
                {
                    b.Navigation("AccountUsers");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BlogCategory", b =>
                {
                    b.Navigation("BlogPostCategories");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.BlogPost", b =>
                {
                    b.Navigation("BlogPostCategories");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Company", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Projects");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("PaymentProof");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("PlanFeatures");

                    b.Navigation("PlanLimits");

                    b.Navigation("PlanPricings");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Project", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.Property", b =>
                {
                    b.Navigation("AmenitySelections");

                    b.Navigation("Images");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.PropertyAmenity", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.RbacPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.RbacRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Boioot.Domain.Entities.User", b =>
                {
                    b.Navigation("AccountUsers");

                    b.Navigation("Agent");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
