// <auto-generated />
using Boioot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Boioot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BoiootDbContext))]
    [Migration("20260415160000_EnhanceUserImages")]
    partial class EnhanceUserImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal — runtime only needs Up()/Down() for migration execution.
        }
    }
}
